config:
    required: true

database:
    +:
        name: default
        package: src.Model
        namespace: App\Model
        defaultIdMethod: native
        identifierQuoting: true

    +vendor:
        type: mysql
        parameters:
            Engine: InnoDB
            Charset: utf8

    +behavior:
        - auto_add_pk

#    content_block:
#        data: longvarchar

# user tables =======
    user:
        type: tinyint
        first_name: longvarchar
        last_name: longvarchar
        middle_name: longvarchar
        email: varchar(255)
        phone: varchar(255)
        password: varchar(255)
        salt: varchar(255)
        +behavior:
            - timestampable

    user_access_token:
        user_id: int > user.id
        token: varchar(64) key
        refresh_token: varchar(64) key
        expired_at:
            - datetime
        +behavior:
            - timestampable

    user_group:
        title: varchar(255)
        name: varchar(50) key(10)
        roles: longvarchar

    user_group_rel:
        user_id: int > user.id
        user_group_id: int > user_group.id
# =======

# page and content tables ======
    content:
        text: clob
        completed: bool
        +behavior:
            - timestampable

    page_site:
        title: longvarchar
        host: longvarchar
        +behavior:
            - sortable
            - timestampable

    content_block:
        data: longvarchar
        type: varchar(20)
        size: tinyint(4)
        visible: bool
        +behavior:
            - tree
            - sortable

    page:
        link_id: int
        page_site_id: int > page_site.id
        type: tinyint(4)
        slug: longvarchar
        url: longvarchar
        title: longvarchar
        menu_title: longvarchar
        name: longvarchar
        host: longvarchar
        meta_title: longvarchar
        meat_description: longvarchar
        meta_keywords: longvarchar
        visible: bool
        hide: bool
        +behavior:
            - tree
            - content
            - sortable
            - timestampable

    holder:
        complete: bool
        page_id: int > page.id
# =======

# files tables =======
    file:
        path: longvarchar
        name: longvarchar
        original_name: longvarchar
        extension: varchar(10)
        mime: varchar(100)
        size: int
        +behavior:
            - timestampable

    gallery:
        +behavior:
            - timestampable

    video:
        source: longvarchar
        +behavior:
            - file
            - timestampable

    image:
        source: longvarchar
        +behavior:
            - file
            - timestampable

    gallery_item:
        gallery_id: int > gallery.id
        title: longvarchar
        description: longvarchar
        cover: bool
        visible: bool
        +behavior:
            - sortable
            - timestampable
            - file
            - image
            - video
# =======

# storage data tables ======
    storage_data_entry:
        item_name: longvarchar
        locale: varchar(10)
        context: longvarchar
        visible: bool
        +behavior:
            - sortable
            - timestampable

    storage_data_field:
        storage_data_entry_id: int > storage_data_entry.id
        field_name: longvarchar
        locale: varchar(10)
        value: longvarchar
        +behavior:
            - timestampable
# =======

# product category brand tables=======
    brand:
        name: longvarchar
        image: longvarchar

    product:
        brand_id: int > brand.id
        price: double(9,2)
        rating: tinyint(5)
        article: longvarchar
        name: longvarchar
        slug: longvarchar
        main_image: longvarchar
        content: longvarchar
        description: longvarchar
        properties: longvarchar
        images_list: longvarchar
        +behavior:
            - timestampable
            - sortable

    product_category:
        name: longvarchar
        image: longvarchar
        content: longvarchar
        products_amount: int

    product_category_rel:
        product_id: int > product.it
        category_id: int > product_category.id

    rating:
        product_id: int > product.id
        user_id: int > user_id
        rate: tinyint(5)
# =======
