<?php

    namespace App\Admin\Catalog;

    use Creonit\AdminBundle\Component\Request\ComponentRequest;
    use Creonit\AdminBundle\Component\Response\ComponentResponse;
    use Creonit\AdminBundle\Component\Scope\Scope;
    use Creonit\AdminBundle\Component\TableComponent;
    use Symfony\Component\HttpFoundation\ParameterBag;

    class ChooseProductBrand extends TableComponent
    {
        /**
         * @title Выберите бренд
         *
         * \ProductBrand
         * @col {{ id }}
         * @col {{ title | controls(buttons(button('', {size: 'xs', icon: 'edit'}) | open('ProductBrandEditor', {key: _key}))) }}
         * @col {{ image_id }}
         *
         * @col
         * {{ title | action('external', _key, title) | controls }}
         *
         */
        public function schema()
        {
        }

//        protected function decorate(ComponentRequest $request, ComponentResponse $response, ParameterBag $data, $entity, Scope $scope, $relation, $relationValue, $level)
//        {
//            parent::decorate($request, $response, $data, $entity, $scope, $relation, $relationValue, $level); // TODO: Change the autogenerated stub
//        }
    }
